print('Aula 09 - Manipulando String')
frase = 'Curso em Vídeo Python'
print('1)',frase)
print('2)',frase[3])
print('3)',frase[3:13])
print('4)',frase[:13])
print('5)',frase[9:])
print('6)',frase[1:15:2])
print('7)',frase[1::2])
print('8)',frase.count('o'))
print('9)',len(frase))
frase1 = '   Curso em Vídeo Python  '
print('10)',frase1.strip())
print('11)',frase1.replace('Python','Android').strip())
print('12)',frase.upper())
print('13)',frase.lower().capitalize())
print('14)','Curso' in frase)
dividido = frase.split()
print('15)',dividido)
print('16)',dividido[0])
print('17)','-'.join(dividido))
