print ('Exercício 4: Analisando Varíaveis')
a = input('Digite Algo: ')
print('O tipo primitivo do valor {}'.format(type(a)))
print('Só tem espaços? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print('É alfanumérico? {}'.format(a.isalnum()))
print('Está em maiúscula? {}'.format(a.isupper()))
print('Está em minusculas? {}'.format(a.islower()))
print('Está capitalizada? {}'.format(a.istitle()))
