print('Exercício: 027 - Primeiro e último Nome')
n = str(input('Digite o Nome Completo: ')).strip()
print ("Muito prazer {} !".format(n))
nome = n.split()
print("O seu primeiro nome é: {} ".format(nome[0]))
print("O seu último nome é:  {}".format(nome[len(nome)-1]))